# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0657fd025d0ae8de9c71f10d779425be9faa99214c162f74861c507e598960e309d8403348b3639b75ee067f25edf9cf7aaaa5e9c085762db1af2945b4826713

test:
  secret_key_base: ac222c910c0105643df6e40e9e98a1fd5c91985666300c4417392e5002bb25c480fc4cba0a404f3eca67b647eaa26cde71b7c2535ace052bc88b20a07bdd648f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
